name: prosthesis-ai-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.1
  - pandas=1.5.3
  - scipy=1.10.0
  - matplotlib=3.7.1
  - scikit-learn=1.1.3
  - librosa=0.9.2
  - pywt=1.3.0
  - tensorflow=2.11.0
  - tensorflow-lite=2.11.0
  - pyyaml=6.0
  - pip
  - pip:
    - tensorflow-hub
